[project]
name = "ontology-industries-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.123.5",
    "pydantic-settings>=2.12.0",
    "typedb-driver>=3.7.0",
]
